renamed UnregisterUserBody to UnregisterUserTutorialBody because Swagger was throwing a fit:
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - CodeEditorApi.Features.Tutorials.TutorialsController.UnregisterUserTutorials (CodeEditorApi). See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - CodeEditorApi.Features.Tutorials.UnregisterUser.UnregisterUserBody. See inner exception
 ---> System.InvalidOperationException: Can't use schemaId "$UnregisterUserBody" for type "$CodeEditorApi.Features.Tutorials.UnregisterUser.UnregisterUserBody". The same schemaId is already used for type "$CodeEditorApi.Features.Courses.UnregisterUser.UnregisterUserBody"